version: '3.8'

services:

  simple-web-service:
    image: devopsdockeruh/simple-web-service
    build: .
    container_name: simple-web-service-compose
    ports:
      - 8080:8080
    command: server
