FROM node:16

#runs in 5000
EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

# old line: ENV REACT_APP_BACKEND_URL=http://localhost:8080

ENV REACT_APP_BACKEND_URL=http://localhost/api/

RUN npm install

RUN npm install -g serve

# build static files with npm run build
RUN npm run build

CMD ["serve", "-s", "-l", "5000", "build"]
